# Iniciar sesion
POST {{URL}}/auth
Content-Type: application/json

{
    "email": "luisibarra@gmail.com",
    "clave": "adahealth1234"
}

{% 

local body = context.json_decode(context.result.body)

context.set_env("accessToken", body.accessToken)

%}

