# Retorna todos los departamentos
GET {{URL}}/lugares/departamentos

# Sube los departamentos a la base de datos
POST {{URL}}/lugares/departamentos
Content-Type: application/json

{ "arrayDepartamentos": {{DEPARTAMENTOS}} }

# Obtiene los municipios de un departamento especifico
GET {{URL}}/lugares/municipios/{{DEPARTAMENTO_ID}}

