# Trae todas las ordenes medicas
GET {{URL}}/ordenes-medicas?skip=0&limit=0
Accept: application/json
Authorization: Bearer {{accessToken}}

###

# Trae las ordenes medicas de un paciente logueado
GET {{URL}}/ordenes-medicas/mis-ordenes
Accept: application/json
Authorization: Bearer {{accessToken}}

###

# crea una orden medica
POST {{URL}}/ordenes-medicas/crear
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "medico": "6548d3e4cb8aa182675b1473",
  "paciente": "6549308cf259f8c86ce76c6b",
  "tipoPruebaLaboratorio": "65492ea1b1651a2e4cf9b234"
}

###

# edita una orden medica
PUT {{URL}}/ordenes-medicas/65495ae51284faf8a76606f8
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "medico": "",
  "paciente": "",
  "tipoPrueba": ""
}

###

# elimina una orden medica
DELETE {{URL}}/ordenes-medicas/65495725848846200df05f77
Content-Type: application/json
Authorization: Bearer {{accessToken}}

