# Retorna todos los parametros pedidos
GET {{URL}}/parametros?parametrosQuery=Rol,EstadoCitaLaboratorio
Accept: application/json

# Retorna el id del valor de un parametro especifico por nombre
GET {{URL}}/parametros/Rol?nombre=administrador

