# Trae todas las sedes de laboratorio
GET {{URL}}/sedes-laboratorios?skip=0&limit=0
Accept: application/json
Authorization: Bearer {{accessToken}}

###

# crea una sede de laboratorio
POST {{URL}}/sedes-laboratorios/crear
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "nombre": "Sede principal",
  "direccion": "Calle 123",
  "municipio": "6547b48d0e7302b163fce121"
}

###

# edita una sede de laboratorio
PUT {{URL}}/sedes-laboratorios/65495ae51284faf8a76606f8
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "medico": "",
  "paciente": "",
  "tipoPrueba": ""
}

###

# elimina una sede de laboratorio
DELETE {{URL}}/ordenes-medicas/65495725848846200df05f77
Content-Type: application/json
Authorization: Bearer {{accessToken}}


