# Trae todos los usuarios
GET {{URL}}/usuarios?skip=0&limit=0
Accept: application/json

###

# Crea un usuario
POST {{URL}}/usuarios/crear
Content-Type: application/json

{
    "tipoDocumento": "6546d8dfe7c0410f3f1f367d",
    "numeroDocumento": "1548342852",
    "nombres": "Andrea",
    "apellidos": "Becerra",
    "fechaNacimiento": "1994-12-24",
    "genero": "6546d753e7c0410f3f1f366c",
    "tipoSangre": "6546d7cde7c0410f3f1f3671",
    "rol": "65465c9ce7c0410f3f1f3662",
    "rh": "6546d76de7c0410f3f1f366e",
    "telefono": 3213456678,
    "clave": "adahealth1234",
    "email": "andreabecerra@gmail.com"
}

###

# Crea un administrador
POST {{URL}}/usuarios/crear-admin
Content-Type: application/json

{
    "tipoDocumento": "6546d8dfe7c0410f3f1f367d",
    "numeroDocumento": "1424131594",
    "nombres": "Luis",
    "apellidos": "Ibarra",
    "fechaNacimiento": "1990-04-28",
    "genero": "6546d734e7c0410f3f1f366b",
    "tipoSangre": "6546d7cde7c0410f3f1f3671",
    "rh": "6546d78fe7c0410f3f1f366f",
    "telefono": 3120123456,
    "clave": "adahealth1234",
    "email": "luisibarra@gmail.com"
}

