# Trae todos los usuarios
GET {{URL}}/usuarios?skip=0&limit=0
Accept: application/json
Authorization: Bearer {{accessToken}}

###

# Crea un usuario
POST {{URL}}/usuarios/crear
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "tipoDocumento": "6546d8dfe7c0410f3f1f367d",
    "numeroDocumento": "1324563543",
    "nombres": "Carolina",
    "apellidos": "Gutierrez",
    "fechaNacimiento": "1995-10-12",
    "genero": "6546d753e7c0410f3f1f366c",
    "tipoSangre": "6546d7cde7c0410f3f1f3671",
    "rol": "65465c6fe7c0410f3f1f3660",
    "rh": "6546d76de7c0410f3f1f366e",
    "telefono": 3215357453,
    "clave": "adahealth1234",
    "email": "caroguti@gmail.com"
}

###

# Crea un administrador
POST {{URL}}/usuarios/crear-admin
Content-Type: application/json

{
    "tipoDocumento": "6546d8dfe7c0410f3f1f367d",
    "numeroDocumento": "1424131594",
    "nombres": "Luis",
    "apellidos": "Ibarra",
    "fechaNacimiento": "1990-04-28",
    "genero": "6546d734e7c0410f3f1f366b",
    "tipoSangre": "6546d7cde7c0410f3f1f3671",
    "rh": "6546d78fe7c0410f3f1f366f",
    "telefono": 3120123456,
    "clave": "adahealth1234",
    "confirmarClave": "adahealth1234",
    "email": "luisibarra@gmail.com"
}

###

# Actualiza un usuario
PUT {{URL}}/usuarios/{{ID_USUARIO}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "tipoDocumento": "6546d8dfe7c0410f3f1f367d",
    "numeroDocumento": "1548342852",
    "nombres": "Andrea",
    "apellidos": "Becerra",
    "fechaNacimiento": "1995-12-24",
    "genero": "6546d753e7c0410f3f1f366c",
    "tipoSangre": "6546d7cde7c0410f3f1f3671",
    "rol": "65465c9ce7c0410f3f1f3662",
    "rh": "6546d76de7c0410f3f1f366e",
    "telefono": 3213456678,
    "email": "andreabecerra@gmail.com"
}

###

# Elimina un usuario
DELETE {{URL}}/usuarios/{{ID_USUARIO}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
